cd ..\Debug

mklink debug.ps.hlsl ..\assets\debug.ps.hlsl
mklink debug.vs.hlsl ..\assets\debug.vs.hlsl
mklink debug.gs.hlsl ..\assets\debug.gs.hlsl
mklink default.constants.hlsl ..\assets\default.constants.hlsl
mklink default.ps.hlsl ..\assets\default.ps.hlsl
mklink default.vs.hlsl ..\assets\default.vs.hlsl
mklink default.gs.hlsl ..\assets\default.gs.hlsl
mklink deferred.constants.hlsl ..\assets\deferred.constants.hlsl
mklink deferred.ps.hlsl ..\assets\deferred.ps.hlsl
mklink deferred.vs.hlsl ..\assets\deferred.vs.hlsl
mklink lighting.hlsl ..\assets\lighting.hlsl
mklink definitions.hlsl ..\assets\definitions.hlsl
mklink functions.hlsl ..\assets\functions.hlsl
mklink water.vs.hlsl ..\assets\water.vs.hlsl
mklink water.ps.hlsl ..\assets\water.ps.hlsl
mklink water.common.hlsl ..\assets\water.common.hlsl
mklink debugtext.vs.hlsl ..\assets\debugtext.vs.hlsl
mklink debugtext.ps.hlsl ..\assets\debugtext.ps.hlsl
mklink debugtext.common.hlsl ..\assets\debugtext.common.hlsl

mklink libfbxsdk.dll "C:\Program Files\Autodesk\FBX\FBX SDK\2015.1\lib\vs2013\x86\debug\libfbxsdk.dll"
mklink mesh.test.fbx ..\assets\mesh.test.fbx
mklink sponza.fbx ..\assets\sponza.fbx
mklink sphere.fbx ..\assets\sphere.fbx

mklink test.tga ..\assets\test.tga
mklink background.tga ..\assets\background.tga
mklink background_ddn.tga ..\assets\background_ddn.tga
mklink chain_texture.tga ..\assets\chain_texture.tga
mklink chain_texture_ddn.tga ..\assets\chain_texture_ddn.tga
mklink chain_texture_mask.tga ..\assets\chain_texture_mask.tga
mklink lion.tga ..\assets\lion.tga
mklink lion2_ddn.tga ..\assets\lion2_ddn.tga
mklink lion_ddn.tga ..\assets\lion_ddn.tga
mklink spnza_bricks_a_ddn.tga ..\assets\spnza_bricks_a_ddn.tga
mklink spnza_bricks_a_diff.tga ..\assets\spnza_bricks_a_diff.tga
mklink spnza_bricks_a_spec.tga ..\assets\spnza_bricks_a_spec.tga
mklink sponza_arch_ddn.tga ..\assets\sponza_arch_ddn.tga
mklink sponza_arch_diff.tga ..\assets\sponza_arch_diff.tga
mklink sponza_arch_spec.tga ..\assets\sponza_arch_spec.tga
mklink sponza_ceiling_a_diff.tga ..\assets\sponza_ceiling_a_diff.tga
mklink sponza_ceiling_a_spec.tga ..\assets\sponza_ceiling_a_spec.tga
mklink sponza_column_a_ddn.tga ..\assets\sponza_column_a_ddn.tga
mklink sponza_column_a_diff.tga ..\assets\sponza_column_a_diff.tga
mklink sponza_column_a_spec.tga ..\assets\sponza_column_a_spec.tga
mklink sponza_column_b_ddn.tga ..\assets\sponza_column_b_ddn.tga
mklink sponza_column_b_diff.tga ..\assets\sponza_column_b_diff.tga
mklink sponza_column_b_spec.tga ..\assets\sponza_column_b_spec.tga
mklink sponza_column_c_ddn.tga ..\assets\sponza_column_c_ddn.tga
mklink sponza_column_c_diff.tga ..\assets\sponza_column_c_diff.tga
mklink sponza_column_c_spec.tga ..\assets\sponza_column_c_spec.tga
mklink sponza_curtain_blue_diff.tga ..\assets\sponza_curtain_blue_diff.tga
mklink sponza_curtain_diff.tga ..\assets\sponza_curtain_diff.tga
mklink sponza_curtain_green_diff.tga ..\assets\sponza_curtain_green_diff.tga
mklink sponza_details_diff.tga ..\assets\sponza_details_diff.tga
mklink sponza_details_spec.tga ..\assets\sponza_details_spec.tga
mklink sponza_fabric_blue_diff.tga ..\assets\sponza_fabric_blue_diff.tga
mklink sponza_fabric_diff.tga ..\assets\sponza_fabric_diff.tga
mklink sponza_fabric_green_diff.tga ..\assets\sponza_fabric_green_diff.tga
mklink sponza_fabric_spec.tga ..\assets\sponza_fabric_spec.tga
mklink sponza_flagpole_diff.tga ..\assets\sponza_flagpole_diff.tga
mklink sponza_flagpole_spec.tga ..\assets\sponza_flagpole_spec.tga
mklink sponza_floor_a_diff.tga ..\assets\sponza_floor_a_diff.tga
mklink sponza_floor_a_spec.tga ..\assets\sponza_floor_a_spec.tga
mklink sponza_roof_diff.tga ..\assets\sponza_roof_diff.tga
mklink sponza_thorn_ddn.tga ..\assets\sponza_thorn_ddn.tga
mklink sponza_thorn_diff.tga ..\assets\sponza_thorn_diff.tga
mklink sponza_thorn_mask.tga ..\assets\sponza_thorn_mask.tga
mklink sponza_thorn_spec.tga ..\assets\sponza_thorn_spec.tga
mklink vase_ddn.tga ..\assets\vase_ddn.tga
mklink vase_dif.tga ..\assets\vase_dif.tga
mklink vase_hanging.tga ..\assets\vase_hanging.tga
mklink vase_plant.tga ..\assets\vase_plant.tga
mklink vase_plant_mask.tga ..\assets\vase_plant_mask.tga
mklink vase_plant_spec.tga ..\assets\vase_plant_spec.tga
mklink vase_round.tga ..\assets\vase_round.tga
mklink vase_round_ddn.tga ..\assets\vase_round_ddn.tga
mklink vase_round_spec.tga ..\assets\vase_round_spec.tga

cd ..\x64\Debug

mklink debug.ps.hlsl ..\..\assets\debug.ps.hlsl
mklink debug.vs.hlsl ..\..\assets\debug.vs.hlsl
mklink debug.gs.hlsl ..\..\assets\debug.gs.hlsl
mklink default.constants.hlsl ..\..\assets\default.constants.hlsl
mklink default.ps.hlsl ..\..\assets\default.ps.hlsl
mklink default.vs.hlsl ..\..\assets\default.vs.hlsl
mklink default.gs.hlsl ..\..\assets\default.gs.hlsl
mklink deferred.constants.hlsl ..\..\assets\deferred.constants.hlsl
mklink deferred.ps.hlsl ..\..\assets\deferred.ps.hlsl
mklink deferred.vs.hlsl ..\..\assets\deferred.vs.hlsl
mklink lighting.hlsl ..\..\assets\lighting.hlsl
mklink definitions.hlsl ..\..\assets\definitions.hlsl
mklink functions.hlsl ..\..\assets\functions.hlsl
mklink water.vs.hlsl ..\..\assets\water.vs.hlsl
mklink water.ps.hlsl ..\..\assets\water.ps.hlsl
mklink water.common.hlsl ..\..\assets\water.common.hlsl
mklink debugtext.vs.hlsl ..\..\assets\debugtext.vs.hlsl
mklink debugtext.ps.hlsl ..\..\assets\debugtext.ps.hlsl
mklink debugtext.common.hlsl ..\..\assets\debugtext.common.hlsl

mklink libfbxsdk.dll "C:\Program Files\Autodesk\FBX\FBX SDK\2015.1\lib\vs2013\x64\debug\libfbxsdk.dll"
mklink mesh.test.fbx ..\..\assets\mesh.test.fbx
mklink sponza.fbx ..\..\assets\sponza.fbx
mklink sphere.fbx ..\..\assets\sphere.fbx

mklink test.tga ..\..\assets\test.tga
mklink background.tga ..\..\assets\background.tga
mklink background_ddn.tga ..\..\assets\background_ddn.tga
mklink chain_texture.tga ..\..\assets\chain_texture.tga
mklink chain_texture_ddn.tga ..\..\assets\chain_texture_ddn.tga
mklink chain_texture_mask.tga ..\..\assets\chain_texture_mask.tga
mklink lion.tga ..\..\assets\lion.tga
mklink lion2_ddn.tga ..\..\assets\lion2_ddn.tga
mklink lion_ddn.tga ..\..\assets\lion_ddn.tga
mklink spnza_bricks_a_ddn.tga ..\..\assets\spnza_bricks_a_ddn.tga
mklink spnza_bricks_a_diff.tga ..\..\assets\spnza_bricks_a_diff.tga
mklink spnza_bricks_a_spec.tga ..\..\assets\spnza_bricks_a_spec.tga
mklink sponza_arch_ddn.tga ..\..\assets\sponza_arch_ddn.tga
mklink sponza_arch_diff.tga ..\..\assets\sponza_arch_diff.tga
mklink sponza_arch_spec.tga ..\..\assets\sponza_arch_spec.tga
mklink sponza_ceiling_a_diff.tga ..\..\assets\sponza_ceiling_a_diff.tga
mklink sponza_ceiling_a_spec.tga ..\..\assets\sponza_ceiling_a_spec.tga
mklink sponza_column_a_ddn.tga ..\..\assets\sponza_column_a_ddn.tga
mklink sponza_column_a_diff.tga ..\..\assets\sponza_column_a_diff.tga
mklink sponza_column_a_spec.tga ..\..\assets\sponza_column_a_spec.tga
mklink sponza_column_b_ddn.tga ..\..\assets\sponza_column_b_ddn.tga
mklink sponza_column_b_diff.tga ..\..\assets\sponza_column_b_diff.tga
mklink sponza_column_b_spec.tga ..\..\assets\sponza_column_b_spec.tga
mklink sponza_column_c_ddn.tga ..\..\assets\sponza_column_c_ddn.tga
mklink sponza_column_c_diff.tga ..\..\assets\sponza_column_c_diff.tga
mklink sponza_column_c_spec.tga ..\..\assets\sponza_column_c_spec.tga
mklink sponza_curtain_blue_diff.tga ..\..\assets\sponza_curtain_blue_diff.tga
mklink sponza_curtain_diff.tga ..\..\assets\sponza_curtain_diff.tga
mklink sponza_curtain_green_diff.tga ..\..\assets\sponza_curtain_green_diff.tga
mklink sponza_details_diff.tga ..\..\assets\sponza_details_diff.tga
mklink sponza_details_spec.tga ..\..\assets\sponza_details_spec.tga
mklink sponza_fabric_blue_diff.tga ..\..\assets\sponza_fabric_blue_diff.tga
mklink sponza_fabric_diff.tga ..\..\assets\sponza_fabric_diff.tga
mklink sponza_fabric_green_diff.tga ..\..\assets\sponza_fabric_green_diff.tga
mklink sponza_fabric_spec.tga ..\..\assets\sponza_fabric_spec.tga
mklink sponza_flagpole_diff.tga ..\..\assets\sponza_flagpole_diff.tga
mklink sponza_flagpole_spec.tga ..\..\assets\sponza_flagpole_spec.tga
mklink sponza_floor_a_diff.tga ..\..\assets\sponza_floor_a_diff.tga
mklink sponza_floor_a_spec.tga ..\..\assets\sponza_floor_a_spec.tga
mklink sponza_roof_diff.tga ..\..\assets\sponza_roof_diff.tga
mklink sponza_thorn_ddn.tga ..\..\assets\sponza_thorn_ddn.tga
mklink sponza_thorn_diff.tga ..\..\assets\sponza_thorn_diff.tga
mklink sponza_thorn_mask.tga ..\..\assets\sponza_thorn_mask.tga
mklink sponza_thorn_spec.tga ..\..\assets\sponza_thorn_spec.tga
mklink vase_ddn.tga ..\..\assets\vase_ddn.tga
mklink vase_dif.tga ..\..\assets\vase_dif.tga
mklink vase_hanging.tga ..\..\assets\vase_hanging.tga
mklink vase_plant.tga ..\..\assets\vase_plant.tga
mklink vase_plant_mask.tga ..\..\assets\vase_plant_mask.tga
mklink vase_plant_spec.tga ..\..\assets\vase_plant_spec.tga
mklink vase_round.tga ..\..\assets\vase_round.tga
mklink vase_round_ddn.tga ..\..\assets\vase_round_ddn.tga
mklink vase_round_spec.tga ..\..\assets\vase_round_spec.tga

pause
